title: APS Born Digital Collections
email: borndigital@amphilsoc.org
description: >- # this means to ignore newlines until "baseurl:"
  American Philosophical Society website for exploring directories of born digital materials.
baseurl: /APS-born-digital-collections # the subpath of your site, e.g. /blog
url: "https://AmericanPhilosophicalSociety.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

last_edit_timestamp: true
last_edit_time_format: "%B %e %Y"
